algoritmo "algoritmo7"
var
   A, B : inteiro
   resultado : real
inicio
      escreva("Digite o valor A: ")
      leia(A)

      //complete o algoritmo:
                 // - Receba o valor B
                 // - Faça uma operação aritmética qualquer e armazene na variável resultado
                 // - Imprima o resultado na tela
                 
      
      escreva("A = ", A)
fimalgoritmo
