algoritmo "algoritmo7"
//EXERCÍCIO 02
//Escrever um algoritmo para receber a idade de uma pessoa.
//Seu algoritmo deve informar se a pessoa é maior ou menor de idade.
var
   idade : inteiro
inicio
      //entrada de dados
      escreva("Digite a idade: ")
      leia(idade)
      
      //processamento e saída de resultados
      se (idade >= 18) entao
         escreva("Maior de idade")
      senao
         escreva("Menor de idade")
      fimse
fimalgoritmo
