//Escreva um algoritmo para receber o seu nome e sua idade
//e imprimir os dois valores um ao lado do outro
algoritmo "algoritmo2"
var
   nome : caractere
   idade: inteiro
inicio
      escreva("Digite o nome: ")
      leia(nome)
      
      escreva("Digite a idade: ")
      leia(idade)
      
      //escreva(nome)
      //escreval(idade)
      escreval(nome, " ", idade)

fimalgoritmo
