algoritmo "algoritmo6"
//EXERCÍCIO 01
//Escrever um algoritmo para receber um numero inteiro diferente de zero.
//Seu algoritmo deve informar se o número é positivo ou negativo
var
   num : inteiro
inicio
      //entrada
      escreva("Digite um número: ")
      leia(num)
      //processamento e saída
      se (num > 0) entao
         escreva("Positivo")
      senao
         escreva("Negativo")
      fimse
fimalgoritmo
