algoritmo "algoritmo8"
//EXERCÍCIO 03
//Escrever um algoritmo para receber um número inteiro qualquer
//Seu algoritmo deve informar se o número é par ou ímpar.
var
   num : inteiro
inicio
      //entrada de dados
      escreva("Digite um número: ")
      leia(num)
      
      //processamento e saída de resultados
      se (num mod 2 = 0) entao
         escreva("PAR")
      senao
         escreva("ÍMPAR")
      fimse

fimalgoritmo
